// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrIr8K5VU2crZDe_32nwNBrneyYK3XRO0',
    appId: '1:313832327764:web:3a77bf3a7ed067d426fbc1',
    messagingSenderId: '313832327764',
    projectId: 'fir-flutter-codelab-de5d7',
    authDomain: 'fir-flutter-codelab-de5d7.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-de5d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8sIGBQ4H1vF5_KyNMGLMF7x-9Wydhc10',
    appId: '1:313832327764:android:091d52b555e4259326fbc1',
    messagingSenderId: '313832327764',
    projectId: 'fir-flutter-codelab-de5d7',
    storageBucket: 'fir-flutter-codelab-de5d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe5kpJD71qCtw5DiHRNhUii4w0VeIfC_c',
    appId: '1:313832327764:ios:c79023d1dce54ce026fbc1',
    messagingSenderId: '313832327764',
    projectId: 'fir-flutter-codelab-de5d7',
    storageBucket: 'fir-flutter-codelab-de5d7.appspot.com',
    iosClientId: '313832327764-186nh66hmvi9981sv4hclmkc4r8gfamj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe5kpJD71qCtw5DiHRNhUii4w0VeIfC_c',
    appId: '1:313832327764:ios:c79023d1dce54ce026fbc1',
    messagingSenderId: '313832327764',
    projectId: 'fir-flutter-codelab-de5d7',
    storageBucket: 'fir-flutter-codelab-de5d7.appspot.com',
    iosClientId: '313832327764-186nh66hmvi9981sv4hclmkc4r8gfamj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
